### ISSUE TITLE
第2版 演習問題 2.10.7

### ISSUE THREAD

**Issue by bananadium** [gaku-t/yukie-gunron#2]
とても重宝しております。ありがとうございます。

第2版 演習問題 2.10.7の解答に
```
  \begin{align*}
    &(aN)(H/N) = (bN)(H/N) \\
    &\Leftrightarrow (aN)(b^{-1}N) \in H/N \\
    &\Leftrightarrow ab^{-1}N \in H/N \\
    &\Leftrightarrow ab^{-1} \in H \\
  \end{align*}
```
とありますが、(aN)(H/N)（(bN)(H/N)）は左剰余類なので
```
  \begin{align*}
    &(aN)(H/N) = (bN)(H/N) \\
    &\Leftrightarrow (a^{-1}N)(bN) \in H/N \\
    &\Leftrightarrow a^{-1}bN \in H/N \\
    &\Leftrightarrow a^{-1}b \in H \\
  \end{align*}
```
などとした方がよいのかな、と思いました。

間違っていましたら、ご教示ください。
よろしくお願いいたします。

**Comment by gaku-t** [comment]
@bananadium 
ご指摘ありがとうございます。確かにその解答は間違っていました。(最初の`\Leftrightarrow`が成り立たないですね。)
ご教示いただいた解答でも良かったのですが、個人的な趣味で、`b^{-1}a...`の形に修正しました。
一旦このissueは閉じますが、さらに疑問点などあればコメントを下さい。
このように間違いを指摘していただけるとたいへん助かり、また励みにもなります。 :pray:

**Comment by bananadium** [comment]
@gaku-t 
早速のご対応、ありがとうございます。意味のない指摘にならなくてよかったです。
ご提示いただいた形での修正でも、無論、差し支えありません（ほとんど同じことですね）。
issueの挙動に詳しくないのですが、このコメントで再度openしてしまったら申し訳ありません。
また何かありましたら、お知らせします。失礼します。
